id: P001772
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10788
  title: མཆིམས་མཛོད།
  author: ''
  volumes:
    cfed6fd32661456ab3aeff2df18f7d11:
      image_group_id: I1KG10821
      title: ''
      volume_number: 1
      total_pages: 590
      base_file: v001.txt
    83672293052442dea5fef0e6c5426d43:
      image_group_id: I1KG10822
      title: ''
      volume_number: 2
      total_pages: 782
      base_file: v002.txt
